### ISSUE TITLE
libusb path

### ISSUE THREAD

**Issue by varna9000** [Ors1mer/QuadcastRGB#10]
Hi thanks for the lib.  Now I can switch off those lights!  I'm using the binary on M1 Macbook Pro.

It's not a bug, but rather a local misconfiguration.  If I install `libusb` from homebrew, the path of libusb is different.
```
./quadcastrgb solid
dyld[14106]: Library not loaded: /usr/local/lib/libusb-1.0.0.dylib
  Referenced from: <71089857-B5E3-327B-801E-9A97362B045E>
```

So I just need to make a symlink to the right location so the binary finds it:

```
ln -s /opt/homebrew/Cellar/libusb/1.0.26/lib/libusb-1.0.0.dylib  /usr/local/lib/libusb-1.0.0.dylib
```

**Comment by Ors1mer** [comment]
Hi! I couldn't figure out the problem with homebrew when I did that myself, so thank you for the help. I'll test it out once I have a MacBook at my disposal, and then I'll update the readme.

**Comment by devAbreu** [comment]
I confirm what @varna9000 says, the route needs to be adjusted. And the route is as described. In my case I just execute this: `export DYLD_LIBRARY_PATH=/opt/homebrew/Cellar/libusb/1.0.26/lib:$DYLD_LIBRARY_PATH`

**Comment by Ors1mer** [comment]
I have updated the readme. Thank you all for the help.

Now I am thinking of just distributing static binaries to get rid of this libusb headache completely.
