### ISSUE TITLE
How does "save" work?

### ISSUE THREAD

**Issue by JasurbekNURBOYEV** [Ors1mer/QuadcastRGB#14]
Do we have the knowledge as to how "save" works (to save configs to mic itself, so that program doesn't have to be running)? I once saw in Sony Headphones repo where people were analysing the data sent & received and were trying to replicate them in program. Basically listening and repeating the signal. Is it a similar process here as well or do we have other ways to know how to implement this feature?

**Comment by Ors1mer** [comment]
Hi there!

Yes, the process is similar and it is called reverse engineering.

You can view and test the save function on the **_dev_write_** branch. You should specify `-w` or `--save` flag. **Spoiler: it almost certainly won't work**.

The only mode that works for me is solid, but some users couldn't make it work.

I have captured some packets from quadcastrgb and Ngenuity for you to compare. You can download them from here: https://ors1mer.xyz/downloads/quadcastrgb_and_ngenuity_captures.tgz
