### ISSUE TITLE
[AUR] Installation fails with No rule to make target 'nix/quadcastrgb.1.gz'

### ISSUE THREAD

**Issue by Ezioleq** [Ors1mer/QuadcastRGB#3]
**Environment**
OS: Arch Linux x86_64
Kernel: 6.1.12-zen1-1-zen
Package Manager: yay

**Steps**
1. Proceed to install the package with `yay -S quadcastrgb`
2. An error occurs on `package()` step (NG)

**Reproduction rate**
3/3

**Expected result**
Package is compiled and installed successfully. (OK)

**Additional info**
```
==> Starting package()...
make: *** No rule to make target 'nix/quadcastrgb.1.gz', needed by 'install'.  Stop.
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: quadcastrgb
```

**Comment by Ors1mer** [comment]
I have updated the Makefile, it should work now

The error occurred because I renamed a directory and didn't change its name in the Makefile

**Comment by Ezioleq** [comment]
I can confirm, it works now. Thanks for the quick reply!
