### ISSUE TITLE
HyperX Quadcast S isn't connected.

### ISSUE THREAD

**Issue by Ying112358** [Ors1mer/QuadcastRGB#7]
hello,
when i run quadcastrgb i get the 'HyperX Quadcast S isn't connected' error.

lsusb:

Bus 001 Device 015: ID 03f0:0294 HP, Inc HyperX QuadCast S
Bus 001 Device 014: ID 03f0:028c HP, Inc HyperX QuadCast S

**Comment by Ors1mer** [comment]
The device id `03f0:028c` is supported. Could you report how did you install and launch the program?

The deb and rpm packages from the repository were outdated. I've deleted them and changed README. Now you're able to download a deb or an rpm package from [the latest release](https://github.com/Ors1mer/QuadcastRGB/releases/tag/v1.0.2) if that is what you've done previously.

**Comment by Ying112358** [comment]
works perfectly, thanks for your work.
