### ISSUE TITLE
Initial Help

### ISSUE THREAD

**Issue by lukewarm110** [Ors1mer/QuadcastRGB#9]
Hello!

I have recently purchased a HyperX Quadcast S only to discover Ngenuity is not compatible on MacOS. I ran across this program in hopes that I still may be able to change the microphone lights instead of returning the device altogether. However, I have no experience in coding whatsoever, and am a tad stuck of how to use your project. Do you have a very basic, step by step guide as to how to get started? I do not wish to create a bunch of work for you, yet a simple bare-bones guideline would be greatly appreciated. Thank you in advance!

Hope you are having a wonderful holiday season,
Luke

**Comment by Ors1mer** [comment]
You are not the only one who asks about MacOS, so it's time to do something about it.

I'll see what I can do in the next few days until the New Year. My plan for Macs is to compile a binary that you can download and run. That would be the simplest way.

I'll update the issue once I have some work done.

**Comment by Ors1mer** [comment]
Sorry for the delay.

I have added the MacOS section in README. It guides you through assuming you do not have any experience with the terminal and command line interface. Be sure to re-open the issue if something is not clear!
